#!/usr/bin/env python3
"""Cost-to-serve model for one tracked query per month.

All unit prices were verified on 2026-10-06 (see docs/research). Token counts per
LLM call are ASSUMPTIONS until measured with the Anthropic count_tokens endpoint
on real AI Overview payloads; change the constants and re-run:

    python3 scripts/unit_economics.py > docs/unit-economics.md
"""

# ---- verified unit prices (USD) -------------------------------------------
DFS_STANDARD_SERP = 0.0006          # DataForSEO Standard queue, per SERP (10 results)
DFS_ASYNC_AIO = 0.0006              # +1 base price for load_async_ai_overview (refunded if absent)
SERPAPI_PER_SEARCH = 150 / 15000    # Production plan $150 / 15,000 searches
SERPAPI_SEARCHES_PER_CAPTURE = 1.5  # page_token redemption counts as a second search ~50% of the time
DUAL_CAPTURE_SAMPLE = 0.05          # share of captures also sent to SerpApi for cross-provider QA
FIRECRAWL_PER_PAGE = 16 / 5000      # Hobby plan $16 / 5,000 credits, 1 credit per markdown page
INNGEST_PER_EXECUTION = 99 / 1e6    # Pro plan $99 / 1M executions (Free tier covers 50k/month)
EXECUTIONS_PER_CAPTURE = 6

# Claude batch prices per million tokens (50% of list): input, output
HAIKU_BATCH = (0.50, 2.50)
SONNET_BATCH = (1.00, 5.00)
OPUS_BATCH = (2.00, 10.00)
SONNET_SYNC = (2.00, 10.00)
OPUS_SYNC = (4.00, 20.00)

def llm(price, tokens_in, tokens_out):
    return tokens_in / 1e6 * price[0] + tokens_out / 1e6 * price[1]

# ---- assumed call shapes (tokens) -----------------------------------------
EXTRACT = (3000, 2500)      # per unique snapshot: claims, entities, format labels (structured output)
SYNTH = (20000, 4000)       # weekly pattern synthesis over SQL aggregates
PAGE = (7500, 2000)         # per cited page: topics, entities, evidence, questions
MATRIX = (26000, 5000)      # cross-source coverage matrix
BRIEF = (30000, 8000)       # brief generation
SCORE = (15000, 3000)       # draft scoring (sync, user-initiated)

def capture_cost():
    serp = DFS_STANDARD_SERP + DFS_ASYNC_AIO
    fallback = DUAL_CAPTURE_SAMPLE * SERPAPI_PER_SEARCH * SERPAPI_SEARCHES_PER_CAPTURE
    jobs = EXECUTIONS_PER_CAPTURE * INNGEST_PER_EXECUTION
    return serp + fallback + jobs

def analysis_run_cost(pages, extract_model):
    """One pattern refresh + cited-page refresh + coverage matrix (batch)."""
    return (llm(SONNET_BATCH, *SYNTH)
            + pages * (FIRECRAWL_PER_PAGE + llm(extract_model, *PAGE))
            + llm(SONNET_BATCH, *MATRIX))

def query_month(renders_per_day, unique_rate, briefs_per_month, pages, extract_model,
                weekly_refreshes=4, page_refreshes=1, days=30):
    captures = renders_per_day * days
    unique = captures * unique_rate
    cost = {
        "capture (SERP + fallback sample + jobs)": captures * capture_cost(),
        "claim/entity extraction on unique renders": unique * llm(extract_model, *EXTRACT),
        "weekly pattern synthesis": weekly_refreshes * llm(SONNET_BATCH, *SYNTH),
        "cited-page analysis + coverage matrix": page_refreshes * (pages * (FIRECRAWL_PER_PAGE + llm(extract_model, *PAGE)) + llm(SONNET_BATCH, *MATRIX)),
        "briefs (Opus 5.5, batch)": briefs_per_month * llm(OPUS_BATCH, *BRIEF),
    }
    cost["total"] = sum(cost.values())
    return cost

TIERS = [
    # name, price, queries, renders/day, devices, unique rate, briefs per query per month, pages, model
    ("Free trial (7 days, one query)", 0, 1, 1, 1, 0.70, 0, 3, HAIKU_BATCH),
    ("Starter $39 / 15 queries", 39, 15, 1, 1, 0.70, 5/15, 10, HAIKU_BATCH),
    ("Pro $99 / 30 queries, 2 renders/day x 2 devices", 99, 30, 2, 2, 0.55, 1.0, 10, HAIKU_BATCH),
    ("Pro variant: 50 queries, 3 renders/day x 2 devices", 99, 50, 3, 2, 0.50, 1.0, 10, HAIKU_BATCH),
    ("Agency $249 / 150 queries, 1 render/day desktop", 249, 150, 1, 1, 0.70, 0.5, 10, HAIKU_BATCH),
    ("Agency with Pro cadence on every query", 249, 150, 2, 2, 0.55, 0.5, 10, HAIKU_BATCH),
]

def main():
    print("# Unit economics (cost to serve one tracked query per month)\n")
    print("Generated by `scripts/unit_economics.py`. Unit prices are verified as of 2026-10-06; token counts per LLM call are assumptions until measured. Re-run the script after measuring real payloads with `count_tokens`.\n")
    print(f"Per-capture cost: ${capture_cost():.4f} (DataForSEO Standard + async overview ${DFS_STANDARD_SERP + DFS_ASYNC_AIO:.4f}, SerpApi QA sample, Inngest executions). Per unique-render extraction: Haiku ${llm(HAIKU_BATCH, *EXTRACT):.4f}, Sonnet ${llm(SONNET_BATCH, *EXTRACT):.4f} (batch). Brief: Opus batch ${llm(OPUS_BATCH, *BRIEF):.3f}, sync ${llm(OPUS_SYNC, *BRIEF):.3f}. Draft score (sync Sonnet): ${llm(SONNET_SYNC, *SCORE):.3f}.\n")
    print("| Tier | Revenue / query | Renders / month | Cost / query | Gross margin / query | Account margin before infra |")
    print("|---|---|---|---|---|---|")
    for name, price, queries, rpd, devices, uniq, briefs, pages, model in TIERS:
        days = 7 if price == 0 and "7 days" in name else 30
        c = query_month(rpd * devices, uniq, briefs, pages, model,
                        weekly_refreshes=1 if days == 7 else 4, page_refreshes=1, days=days)
        rev = price / queries if price else 0
        margin = (rev - c["total"]) / rev if rev else 0
        acct = price - queries * c["total"]
        print(f"| {name} | ${rev:.2f} | {rpd*devices*days} | ${c['total']:.2f} | {margin*100:.0f}% | ${acct:.0f} |")
    print("\n## Cost breakdown per query-month\n")
    for name, price, queries, rpd, devices, uniq, briefs, pages, model in TIERS:
        days = 7 if price == 0 and "7 days" in name else 30
        c = query_month(rpd * devices, uniq, briefs, pages, model,
                        weekly_refreshes=1 if days == 7 else 4, page_refreshes=1, days=days)
        print(f"**{name}**\n")
        for k, v in c.items():
            print(f"- {k}: ${v:.3f}")
        print()
    print("## Fixed monthly costs not in the table\n")
    print("- SerpApi Production $150 (legal shield and fallback), Vercel Pro $20, Inngest Pro $99 once past 50,000 executions/month, Neon from $0, Firecrawl Hobby $16, Resend/PostHog/Sentry free tiers, Cloudflare R2 under $5 at 1,000 queries.")
    print("- Sentinel canary set: 100 queries x 2 renders/day x 2 devices ≈ 12,000 captures/month ≈ $25.")
    print("\n## What the numbers say\n")
    print("- Capture is cheap; extraction is the lever. Every extra render per day costs about $0.002 to scrape but about $0.005 to $0.016 to extract, so extraction must run only on unique content (hash plus near-duplicate check) and on the cheap tier.")
    print("- A Pro tier at 50 queries with 6 renders/day is marginal on Haiku and loss-making on Sonnet; 30 queries at 4 renders/day keeps a healthy margin. Make cadence a visible tier feature.")
    print("- The Agency tier is only viable at Starter cadence by default; sell multi-render fidelity as a per-query add-on priced at cost plus margin.")
    print("- The free trial costs well under a dollar per signup when the LLM analysis is delayed to day 3 and limited to three cited pages.")

if __name__ == "__main__":
    main()
